spring:
  application:
    name: external-config-demo
server:
  port: 7910


simple:
  config:
    bean:
      enabled: true
      host: externalized-configuration-from-application-yml
      ip: localhost
    annotated:
      enabled: true
      host: annotated-config-bean-from-application-yml
      ip: 127.0.0.1
